newstories/main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

newstories/newstories/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

newstories/main/models.py
from django.db import models

# Create your models here.

newstories/story7/models.py
from django.db import models

# Create your models here.

newstories/main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/home.html')

newstories/story7/views.py
from django.shortcuts import render

# Create your views here.

newstories/main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}

{% endblock content %}

newstories/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <!-- Navigation Bar -->
<div class="offset-1 col-10 text-center">
  <nav class="navbar fixed-top navbar-expand-lg navbar-light">
      <a class="navbar-brand active" href="{% url 'main:home' %}">Ferika <img src="" width="30px"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
          <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home' %}#home">Home</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="https://ferikahafshah.herokuapp.com/">Story1-6</a>
          </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'main:home' %}#story7">Story 7 </a>
          </li>
      </ul>
      </div>
  </nav>
  </div>
  {% block content %}
  {% endblock content %}

      
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    
</body>

</html>